org: afrida1009
app: emailvalidapp
service: aws-email-valid

frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  main:
    handler: handler.validate
    events: 
      - http: POST /email/validate
